---
- name: isntall unattended-upgrades
  apt: name=unattended-upgrades
- copy: src=apt.conf-06suggested
        dest=/etc/apt/apt.conf.d/06suggested
- name: config unattended-upgrades to install from {{debian_release}}-security
  lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades
              regexp="{{debian_release}}-updates"
              state=absent
