---
- name: set logwatch to send to $email daily
  lineinfile: dest=/etc/cron.daily/00logwatch
                  regexp="^/usr/sbin/logwatch"
              line="/usr/sbin/logwatch --output mail --mailto {{admin.email}} --detail high"
              create=yes
