---
- lineinfile: dest=/tmp/resistencia.firstrun
              regexp="ok"
              line="ok"
              create=yes
  register: firstrun
- shell: grep -E "^vagrant:" /etc/shadow
  ignore_errors: yes
  register: under_vagrant
  changed_when: False
- include: hostname.yml
- include: sysctl.yml
- include: apt.yml
- include: git.yml
- apt: name="{{item}}"
  with_items:
    - etckeeper
    - vim-nox
    - sudo
    - selinux-basics
    - selinux-policy-default
    - auditd
    - fail2ban
    - logwatch
    - rkhunter
    - ufw
    - haveged
    - ntp
    - ntpdate
    - gnupg2
    - python-gpgme
    - postfix
    - screen
- include: admin.yml
- include: sudo.yml
- include: firewall.yml
- include: harden.yml
- include: audit.yml
- include: rkhunter.yml
  when: under_vagrant|failed
- include: logwatch.yml
  when: under_vagrant|failed
- include: haveged.yml
- include: bash.yml
- include: ssh.yml
- include: postfix.yml
- include: zeyple.yml
  when: under_vagrant|failed
- include: selinux.yml
- include: services.yml
